### ISSUE TITLE
possible to get labelled generic HList out of BSON?

### ISSUE THREAD

**Issue by raven-stas** [julienrf/reactivemongo-derived-codecs#3]
hi Julien, 
I'm a total beginner with type classes and shapeless in particular. Trying to find a way to get labelled generic HList out of BSON using your library but still ending up doing it the regular way i.e.

```scala
  val bdoc = BSONDocument(
    "itemX" -> BSONInteger(30),
    "itemY" -> BSONString("some_item")
  )

  implicit object HListReader extends BSONDocumentReader[HList] {
    def read(bson: BSONDocument): HList = {
      bson.elements.foldLeft[HList](HNil) { case (res, element) =>
        element match {
          case BSONElement(name, BSONInteger(value)) =>
            (name -> value) :: res

          case BSONElement(name, BSONString(value)) =>
            (name -> value) :: res

          case _ =>
            res

        }
      }
    }
  }

  val doc = HListReader.read(bdoc)
```

Would I be able to use your library to achieve this?

p.s. Sorry for reaching out to you probably in the wrong place

**Comment by julienrf** [comment]
Hey, does the following work?

~~~ scala
val wItemX = Witness("itemX")
val wItemY = Witness("itemY")
type BDoc = FieldType[wItemX.T, Int] :: FieldType[wItemY.T, String] :: HNil

implicit val doc: BSONDocumentReader[BDoc] = derived.codec[BDoc]
~~~

**Comment by raven-stas** [comment]
Thanks for getting back on this, I think I now better understand how `Witness` works :)

If I understand correctly, what you suggest also requires updating base type i.e. if we have BDoc1, BDoc2 and `type BDoc = BDoc1 :+: BDoc2 :+: CNil`, then introducing BDoc3 would require update to BDoc too i.e. `type BDoc = BDoc1 :+: BDoc2 :+: BDoc3 :+: CNil`.

In general is it possible to create decoders for coproducts but without resorting to *sealed traits*?

For instance it's impossible to introduce new BSONValue outside of the library (or is it so?). 

My idea was to use HList when reading from BSON so that introducing new subtypes wouldn't require change in the base code. Don't know how good pattern it is though.

Would you have any ideas or recommendations on this score?

**Comment by julienrf** [comment]
My recommendation is to define case classes and sealed traits in your code base for each kind of document you want to be able to encode/decode.

**Comment by raven-stas** [comment]
Yup, thanks. I guess I'm just closing this one and thanks for quick responses!
